### ISSUE TITLE
error 500 tron

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#12]
I started shkeeper with tron. I started java-tron in docker, threw the settings in values.yaml. I started helm and it gives me the error "Internal Server Error" when going to the page /payout/USDT

values.yaml
```
tron:
  server:
    host: 'localhost'
    port: 50051

usdt:
  enabled: true
usdc:
  enabled: true
```
