### ISSUE TITLE
Problem in connecting with TRON shkeeper-hosted full node

### ISSUE THREAD

**Issue by Phoenix997733** [vsys-host/shkeeper.io#31]
I tried to connect to your full node to be able to process payments without having to download the full node but it seems that the host is not working though.
values.yaml content:

```
cat << EOF > values.yaml

#
# General
#

dev:
  imagePullSecrets:

storageClassName: local-path


#
# BTC and forks
#

btc:
  enabled: true
ltc:
  enabled: true
doge:
  enabled: true


monero:

  enabled: false
  image: vsyshost/monero:v0.18.1.2
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "monerod"
      port: "1111"
      user: "monerod"
      password: "monerod"
      nodeSelector: {}
      tolerations: []

tron_fullnode:
  enabled: true
  url: http://fullnode.tron.shkeeper.io
  image: vsyshost/tron-shkeeper:1.0.14
  host: 'tron-shkeeper'
  port: 6000

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
EOF
```

**Comment by drag0n-flyer** [comment]
In my case shkeeper node was online for few hour but from last one hours its showing Sync in progress (30 blocks behind) than 50 blocks

**Comment by Phoenix997733** [comment]
It didn't work at all for me. What's the content of values.yaml file. Is it different from mine?

**Comment by dmytro-samoylenko** [comment]
Hello,

The fullnode is online, you may check it using curl:

```
$ curl shkeeper:tron@fullnode.tron.shkeeper.io/wallet/getnowblock | cut -c -200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  477k    0  477k    0     0  4081k      0 --:--:-- --:--:-- --:--:-- 4117k
{"blockID":"00000000033c41c65a1d9e53ff81da62cf152e66304797861b111fb80b10eb4c","block_header":{"raw_data":{"number":54280646,"txTrieRoot":"28bc887b2ad848f75a0d739d677ed46583b6ac2c2200081d0c969a56cc39f9
```

You may check tron-shkeeper logs to see if there are any errors.

The following config is enough to use our tron fullnode:

```
tron_fullnode:
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```

You should not set tron_fullnode.enabled to true if your are not wish to run tron fullnode locally.
