### ISSUE TITLE
How install eth?

### ISSUE THREAD

**Issue by bubixon** [vsys-host/shkeeper.io#46]
I added ethereum to my values.yaml file, but what do I need to do more?

#
# General
#

storageClassName: local-path

#
# BTC and forks
#

btc:
  enabled: true
ltc:
  enabled: true
doge:
  enabled: true

#
# Monero
#

monero:
  enabled: true
  fullnode:
    enabled: true

ethereum:
  enabled: true
  fullnode:
    enabled: true

**Comment by anycolo** [comment]
This is what i added, and sometimes it works:


```
eth_fullnode:
  enabled: true
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.0.9

eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true

```
