### ISSUE TITLE
How install eth testnet environment

### ISSUE THREAD

**Issue by thapld** [vsys-host/shkeeper.io#51]
How install eth testnet environment?

**Comment by yukonet** [comment]
You can install SHKeeper with Ethereum testnet crypto using the following steps:

1) Create values.yaml file with next content:

```
storageClassName: local-path
btc:
  enabled: false
ltc:
  enabled: false
doge:
  enabled: false

#
# Ethereum
#

eth_fullnode:
  enabled: true
  mainnet: false
  
eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true
```

2) Install SHKeeper with commands:

```
helm repo add vsys-host https://vsys-host.github.io/helm-charts
helm repo add mittwald https://helm.mittwald.de
helm repo update
helm install kubernetes-secret-generator mittwald/kubernetes-secret-generator
helm install -f values.yaml shkeeper vsys-host/shkeeper
```

If you do not have Kubernetes and Helm installed, you can use the following instructions to install these components:
https://shkeeper.io/kb/start-to-work/documentation-on-launching

Once SHKeeper is installed and your local full testnet node is synchronized, you should add the following variables to the values and update your deployment

```
ethereum_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"
```
