### ISSUE TITLE
Issue with Tron sync

### ISSUE THREAD

**Issue by dw-kodani** [vsys-host/shkeeper.io#54]
In values.yaml, it is defined as follows.

```
#
# TRON
#
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```

But, all TRC tokens have an increasing number of blocks that cannot be fully synced, as in "Sync In Progress (8117 blocks behind)".

Is http://fullnode.tron.shkeeper.io not a public node?
Or does it keep increasing if there are network bandwidth problems?
