### ISSUE TITLE
Server Showing Offline Status in TRON Configuration

### ISSUE THREAD

**Issue by ohblue** [vsys-host/shkeeper.io#56]
I am experiencing an issue where the server status for TRON shows as offline. Below are the contents of my configuration file:
```
#
# TRON
#
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```
As shown, the tron_fullnode is currently set to enabled: false, which I suspect might be related to why the server appears offline. Could this setting be causing the issue, or should I be looking at other potential causes? Any guidance on how to resolve this problem would be greatly appreciated.
Thank you for your assistance.

**Comment by yukonet** [comment]
Hello,
Your configuration is correct if you want to use a public tron ​​fullnode
You should check the tron-shkeeper pod logs

**Comment by Kerrypinny** [comment]
Hello @ohblue 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID TRX07638
Please see the link below to our dedicated support line:
[Tron Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by MingYi0226** [comment]
Hi @yukonet , I have same issue for BNB configuration with following yaml.
```yaml
storageClassName: local-path

#
# BTC and forks
#
btc:
  enabled: false
ltc:
  enabled: false
doge:
  enabled: false

bnb_fullnode:
  enabled: false

bnb:
  enabled: true
bnb_usdt:
  enabled: true
bnb_usdc:
  enabled: true
```
I checked the `bnb-shkeeper` pod logs, and it seems like http connection to fullnode is unreachable.
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='bnb', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b102aab80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
I can see bnb url in [here](https://github.com/vsys-host/helm-charts/blob/5bc9227b029aea858e8dc7893fc9fbe966ae8002/charts/shkeeper/values.yaml#L106C2-L106C23)
```yaml
bnb_fullnode:
  enabled: false
  url: http://bnb:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []
```

Urls in values.yaml has updated or not working?

**Comment by yukonet** [comment]
Hello,

If you want to use a public node instead of your own fullnode, please check the following link: https://shkeeper.io/kb/use-cases/how-to-use-bnb-with-shkeeper-public-fullnode

**Comment by MingYi0226** [comment]
Thank you for your reply @yukonet! Above url works for BNB test network too?

**Comment by yukonet** [comment]
Your values.yaml looks correct
You can check the bnb-shkeeper logs to find the cause of the problem

**Comment by aboozaid** [comment]
> Hello, Your configuration is correct if you want to use a public tron ​​fullnode You should check the tron-shkeeper pod logs

I have the same problem and I get on the log this exception `app.exceptions.NoServerSet: Current server is not set.`.

This is my yaml config
```
#
# TRON
#
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```
