### ISSUE TITLE
how to use tron nile testnet?

### ISSUE THREAD

**Issue by kanggadin** [vsys-host/shkeeper.io#63]
I want to test a TRON wallet using the TRON Nile Testnet. In the values.yaml file, I have set:

#
# TRON
#
tron_fullnode:
  enabled: false
#  url: 
  url: https://nile.trongrid.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true

However, it is not syncing. Is there a way to use the testnet without TronLink?

**Comment by laalauren1** [comment]
> I want to test a TRON wallet using the TRON Nile Testnet. In the values.yaml file, I have set:
> 
> # TRON
> tron_fullnode: enabled: false
> 
> # url:
> url: https://nile.trongrid.io
> 
> trx: enabled: true usdt: enabled: true usdc: enabled: true
> 
> However, it is not syncing. Is there a way to use the testnet without TronLink?

@kanggadin It looks like you're setting up a TRON wallet to test on the TRON Nile Testnet. If you've configured the values.yaml file for this purpose, what specific assistance do you need with the setup or testing process? so I can help you effectively.

**Comment by yukonet** [comment]
Hello,

The correct config for testnet and https://nile.trongrid.io/ external fullnode will be:
```

#
# TRON
#
tron_fullnode:
  enabled: false
  mainnet: false
  url: https://nile.trongrid.io/
trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```
