### ISSUE TITLE
Sync not working with ETH testnet

### ISSUE THREAD

**Issue by secretman04** [vsys-host/shkeeper.io#68]
I had installed SHKeeper in my server and I want to deploy it to the testnet with this values.yaml file. But it keep on showing sync in progress and the block is keep on increasing. What should I do to allow using testnet for ETH in SHKeeper

```
storageClassName: local-path
btc:
  enabled: false
ltc:
  enabled: false
doge:
  enabled: false

#
# Ethereum
#

ethereum_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"

eth_fullnode:
  enabled: true
  mainnet: false

eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true

```
