### ISSUE TITLE
wallet status offline, server offline for multiple currencies

### ISSUE THREAD

**Issue by chostorg** [vsys-host/shkeeper.io#70]
For BNB, BEP20 USDC, BEP20 USDT, Ethereum, ERC20 USDC, ERC20 USDT, the gateway stopped working a few weeks ago. 

Server: Offline
Wallet status: Offline

This is my config:

```
#
# General
#

storageClassName: local-path

#
# BTC and forks
#

btc:
  enabled: false
ltc:
  enabled: false
dogecoin:
  enabled: false
monero:
  enabled: false
doge:
  enabled: false
dogecoin:
  enabled: false


tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true



#
# Ethereum
#
ethereum_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"

eth_fullnode:
  enabled: false
  mainnet: true
  url: https://fullnode.ethereum.shkeeper.io:8645
eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true

#
# BNB
#
bnb_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"

bnb_fullnode:
  enabled: false
  mainnet: true
  url: https://fullnode.bnb.shkeeper.io:8645
bnb:
  enabled: true
bnb_usdt:
  enabled: true
bnb_usdc:
  enabled: true

```

It worked well for a week or two, but sometime, don't know when, payments stopped working for those coins.
This is what i run to update:
```
helm repo update
helm upgrade -f values.yaml shkeeper vsys-host/shkeeper

```
