### ISSUE TITLE
Tron server appears to be offline

### ISSUE THREAD

**Issue by Hattorius** [vsys-host/shkeeper.io#73]
When checking the SHKeeper dashboard the TRON node shows as offline:
![image](https://github.com/user-attachments/assets/9bd2e02a-26e2-41d1-b867-1f4271ad2668)

Using the default config for tron:
```
#
# TRON
#
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```

When going to the node url (http://fullnode.tron.shkeeper.io) it asks for a username & password which is not set.
Any details on this?

**Comment by Hattorius** [comment]
I've fixed this. For anyone who's looking for the solution, you need to set `mainnet` to `true` in the yaml. In the docs and setup process it does that for both ethereum and bnb chain, but not for the tron chain. So update
```
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io
```
to
```
tron_fullnode:
  enabled: false
  mainnet: true
  url: http://fullnode.tron.shkeeper.io
```
