### ISSUE TITLE
Unable to sync nodes (only BTC, LTC and Doge available)

### ISSUE THREAD

**Issue by ChanisCrypto** [vsys-host/shkeeper.io#85]
Good afternoon, I successfully installed SHKeeper on my PC just to try it out first and out of the box there were 3 coins that started working right away - BTC, LTC and Doge. However, I was unable to activate the additional coins that were available (screenshot attached). 

Could you please advise me where I went wrong? Thanks!

![111image_2025-01-09_18-54-53](https://github.com/user-attachments/assets/d18e38b4-75ff-4d37-a45e-85998251efb6)

configuration is following:

```
#
# General
#

namespace: shkeeper
external_ip: 0.0.0.0

dev:
  imagePullSecrets:

storageClassName:

#
# Shkeeper
#

shkeeper:
  image: vsyshost/shkeeper:2.2.4
  port: 5000

#
# BTC and forks
#

btc:
  enabled: false
  mainnet: true
  bitcoind:
    image: vsyshost/bitcoind:27.0

ltc:
  enabled: false
  mainnet: true
doge:
  enabled: false
  mainnet: true

#
# Tron
#

tron_fullnode:
  enabled: true
  url: https://nile.trongrid.io
  solidity_url: http://18.139.193.235:8091
  mainnet: true
  JAVA_TOOL_OPTIONS: ""
  nodeSelector: {}
  tolerations: []

tron_shkeeper:
  image: vsyshost/tron-shkeeper:1.1.2
  host: 'tron-shkeeper'
  port: 6000

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true

#
# Ethereum
#

eth_fullnode:
  enabled: false
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.1.7

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false
eth_pyusd:
  enabled: false

#
# Monero
#

monero:

  enabled: false
  image: vsyshost/monero:v0.18.1.2
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "monerod"
      port: "1111"
      user: "monerod"
      password: "monerod"
      nodeSelector: {}
      tolerations: []

#
# BNB
#

bnb_fullnode:
  enabled: false
  url: http://bnb:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

bnb_shkeeper:
  image: vsyshost/bnb-shkeeper:1.1.5

bnb:
  enabled: false
bnb_usdt:
  enabled: false
bnb_usdc:
  enabled: false

#
# XRP
#

xrp_fullnode:
  enabled: false
  url: http://xrp:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []

xrp_shkeeper:
  image: vsyshost/xrp-shkeeper:1.0.12

xrp:
  enabled: false

#
# Polygon
#

polygon_fullnode:
  enabled: false
  url: http://polygon:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []

polygon_shkeeper:
  image: vsyshost/polygon-shkeeper:1.0.3

matic:
  enabled: false
polygon_usdt:
  enabled: false
polygon_usdc:
  enabled: false

#
# Avalanche
#

avalanche_fullnode:
  enabled: false
  url: http://avalanche:9650/ext/bc/C/rpc
  mainnet: true
  nodeSelector: {}
  tolerations: []

avalanche_shkeeper:
  image: vsyshost/avalanche-shkeeper:1.0.0

avax:
  enabled: false
avalanche_usdt:
  enabled: false
avalanche_usdc:
  enabled: false

#
# BTC Lightning
#

btc_lightning:
  enabled: false
  network: mainnet

  lnd:
    image: vsyshost/lndinit:v0.1.22-beta-lnd-v0.18.3-beta
    rest_url: https://lightning-lnd-rest:8080
    p2p_port: 9735

  rtl:
    image: shahanafarooqui/rtl:v0.15.4
    web_url: http://rtl:3000
    logout_redirect_link: http://shkeeper:5000/wallet/BTC-LIGHTNING
```
