### ISSUE TITLE
No information on how to use a external Monero Node

### ISSUE THREAD

**Issue by Fjox** [vsys-host/shkeeper.io#91]
it was announced that this was possible but i cant find any information on how. 
https://shkeeper.io/news/external-node-capability-for-monero

**Comment by yukonet** [comment]
Hello,

To use Monero with our external fullnode you should add next lines to the values.yaml file (to use other fullnodes, you need to change the host and port):


Lines for mainnet:

```
#
# Monero
#

monero:
  enabled: true
  mainnet: true

    monerod:
      host: "fullnode.monero.shkeeper.io"
      port: "18089"
```

----

Lines for Testnet
```

#
# Monero
#

monero:
  enabled: true
  mainnet: false

    monerod:
      host: "stagenet.monero.shkeeper.io"
      port: "38089"
```

**Comment by Fjox** [comment]
> #
> # Monero
> #
> 
> monero:
>   enabled: true
>   mainnet: true
> 
>     monerod:
>       host: "fullnode.monero.shkeeper.io"
>       port: "18089"

if i try it gives me this error 

```
Error: INSTALLATION FAILED: failed to parse values.yaml: error converting YAML to JSON: yaml: line 25: mapping values are not allowed in this context
```

**Comment by yukonet** [comment]
Sorry, there was an error in the previous config
Please try the following configs

Testnet
```
#
# Monero
#

monero:

  enabled: true
  mainnet: false

  fullnode:
    enabled: false
    monerod:
      host: "stagenet.monero.shkeeper.io"
      port: "38089"
```

Mainnet
```
#
# Monero
#

monero:

  enabled: true
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "fullnode.monero.shkeeper.io"
      port: "18089"
```
