### ISSUE TITLE
Etherum public node not working

### ISSUE THREAD

**Issue by MugenTwo** [vsys-host/shkeeper.io#97]
Hi! I tried to use the etherum public node as per the following guide:

https://shkeeper.io/kb/use-cases/how-to-use-ethereum-with-shkeeper-public-fullnode

but shkeeper is showing inactive:

<img width="849" alt="Image" src="https://github.com/user-attachments/assets/ad50a185-6736-46c8-909c-9d7cd32d0cb1" />

I am also seeing a crashed ethereum pod in the shkeeper namespace:

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/39585286-d87f-44f5-bba2-d1fe035cfab9" />

my values.yaml is:
```
btc:
  enabled: false
  mainnet: false
ltc:
  enabled: false
doge:
  enabled: true
  mainnet: false

ethereum_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"

eth_fullnode:
  enabled: false
  mainnet: true
  url: https://fullnode.ethereum.shkeeper.io:8645
eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true
```

and then I just do a typical helm install with this values.yaml
